# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

LABEL io.openshift.expose-services="8080:http" \
      io.k8s.description="child container for httpd uses ONBUILD" \
      io.k8s.display-name="httpd-child" \
      io.openshift.tags="apache, httpd"

EXPOSE 8080

RUN sed -i "s/Listen80/Listen 8080/g" etc/httpd/conf/httpd.conf && \
    sed -i "s/#SErverName www.example.com:80/ServerName 0.0.0.0:8080/g" /etc/httpd/conf/httpd.conf

RUN chown -R 0 /var/log/httpd /var/run/httpd && \
    chmod -R g=u /var/log/httpd /var/run/httpd
USER 1001
